### PR TITLE
update api version to release-1.4

### PR DESCRIPTION
**Pull request by jasonwzm**

### CODE REVIEW

**Comment by nrjpoddar** [comment]
what's new in this version of istio API that warrants an update?

**Comment by jasonwzm** [comment]
https://github.com/istio/istio/issues/18737 reported the deepcopy method appends repeated fields in protos. The new API version fixed that.

**Comment by nrjpoddar** [comment]
> istio/istio#18737

Makes sense, I was telling @rcernich that we should switch to `proto.Clone` instead of `proto.Merge`. I'm glad you got to it before me. :)

**Comment by nrjpoddar** [comment]
@jasonwzm not a blocker for this PR but it would be great to have unit tests in this repo to verify deepcopy behavior for generated structs that are known to be problematic.

**Comment by jasonwzm** [comment]
Unit test was added to the tools repo: https://github.com/istio/tools/blob/master/cmd/protoc-gen-deepcopy/test/deepcopy_test.go#L66 I agree we need to have more tests overall. Created https://github.com/istio/istio/issues/18825 to keep track as a work item.

**Comment by rcernich** [comment]
This change seems to reintroduce the duplicate package names, where the import name is the same as the local package name.

**Comment by jasonwzm** [comment]
> This change seems to reintroduce the duplicate package names, where the import name is the same as the local package name.

This is because the tools change was not cherrypicked to 1.4 branch. Doing that now.

**Comment by nrjpoddar** [comment]
@rcernich @jasonwzm there seems to be some disconnect here, for me release-1.4 works, so I'm not sure what you both are referring to.

**Pull request merged**
