### PR TITLE
Update licenses for new mirror tool

### PR DESCRIPTION
**Pull request by howardjohn**
This is expected to remove many licenses which where unintentionally
added, and is regenerated following
https://github.com/istio/tools/pull/1216 change to the tool.

These licenses were *not* used by Istio, and were unintentionally
included. The tooling change has TOC approval already.

### CODE REVIEW

**Comment by esnible** [comment]
I don't understand why  `istio/wg-user-experience-maintainers` is expected to provide the only review.

**Comment by howardjohn** [comment]
config wg was the owner. which became UX

**Comment by howardjohn** [comment]
> I have no problem with the removals but don't know how to vet. @sdake , what do you think?

This has already been approved by TOC and merged in every other istio/ repo

**Review by esnible — APPROVED** [review]

**Comment by sdake** [comment]
> I have no problem with the removals but don't know how to vet. @sdake , what do you think?

@esnible I defer all license decisions to the TOC. I don't have the legal contacts to make decisions on these topics, but either steering or TOC should be acting in this capacity.

Cheers,
-steve

**Pull request merged**
