### PR TITLE
Update common files.

### PR DESCRIPTION
**Pull request by geeknoid**
Will need an update in test-infra for all checks to pass.

### CODE REVIEW

**Comment by geeknoid** [comment]
@rcernich Rob, I'm trying to update the common files, which means this is getting a new build-tools container. This results in some code gen differences, which ends up breaking the build.

The build-tools container is defined in istio/tools/docker/build-tools/Dockerfile. The container image being added here was built from the release-1.4 branch of that Dockerfile.

Any ideas?

**Comment by rcernich** [comment]
@geeknoid, are you still having problem?  I suspect the code changes are the result of [this](https://github.com/istio/tools/pull/443).  I've been waiting for a new tools image that contains those changes, so I could regenerate the code.

**Comment by geeknoid** [comment]
Yeah, it's still not working. Note that this is in the 1.4 branch, which is using a container image derived from the 1.4 version of the Dockerfile in tools/docker/build-tools.

So do we need to merge that Dockerfile change to the 1.4 branch then?

**Comment by rcernich** [comment]
Looks like there's a dependency issue with the generated code, `scheme.Codecs.WitihoutConversion()` is undefined.  I suspect this has to do with changes to the k8s dependencies in tools, specifically using new code generators (but I haven't verified).

**Comment by rcernich** [comment]
@geeknoid, feel free to pull this in: https://github.com/rcernich/istio-client-go/commit/59700f742da3c209f56fe17393a46f2b5ff87266

**Comment by rcernich** [comment]
hold on, looks like k8s client-go needs to be updated too.

**Comment by rcernich** [comment]
With [these](https://github.com/rcernich/istio-client-go/commit/63887ebc222971d6a6e3fb53cce5937c8906cd63) changes, the build succeeds.  Notice, there were some additional updates to the generated files when the newer dependencies were introduced.

**Comment by rcernich** [comment]
@geeknoid, for the gencheck job, do you also need to update the prow config to use the latest image?  I wonder if that's part of the problem.

**Pull request merged**
