### PR TITLE
Update client-go to use generators from k8s 1.23

### PR DESCRIPTION
**Pull request by jacob-delgado**

### CODE REVIEW

**Comment by jacob-delgado** [comment]
This is dependent on https://github.com/istio/test-infra/pull/3715

**Review by howardjohn — APPROVED** [review]
No SSA config? Will that be separate PR? Either way is ok with me

**Comment by jacob-delgado** [comment]
> No SSA config? Will that be separate PR? Either way is ok with me

Yeah. I want to get the build in an ok spot. I'm also in the process of updating istio/istio with the changes for 1.23--I had found this out when you had mentioned SSA, see https://github.com/istio/istio/blob/79720fdf353dc741707e3db04926a5f391a12833/pkg/kube/client.go#L898. Do you still want to replace that method with one that uses SSA?

**Review by shamsher31 — APPROVED** [review]

**Comment by howardjohn** [comment]
> I'm also in the process of updating istio/istio with the changes for 1.23--I had found this out when you had mentioned SSA, see https://github.com/istio/istio/blob/79720fdf353dc741707e3db04926a5f391a12833/pkg/kube/client.go#L898. Do you still want to replace that method with one that uses SSA?

I think this is a bit orthogonal to 1.23 fwiw. I was talking about the applyconfigurations generator stuff in my previous comment, which is used for when you are applying an object directly from go code and building the objects in go. That is applying yaml files, so a bit different. If it works with SSA - great. I vaguely recall trying it a while back and having issues but I forget why. The code is only used in tests AFAIK, so if tests pass and the code is simpler then its good IMO

**Pull request merged**
