### PR TITLE
Don't rename doc.go since it's expected by k8s code generator

### PR DESCRIPTION
**Pull request by skaslev**
Currently fake client-go client sets are broken, e.g. we have[1]

  var gatewaysResource = schema.GroupVersionResource{Group: "networking", Version: "v1alpha3", Resource: "gateways"}

which should really be

  var gatewaysResource = schema.GroupVersionResource{Group: "networking.istio.io", Version: "v1alpha3", Resource: "gateways"}

This is because
 1. kubetype-gen generated apis are missing groupName comment tag (addressed by istio/tools#549)
 2. k8s code generator expects groupName comment tag to be in doc.go but it is currently getting renamed to doc.gen.go

This change fixes 2.

[1] https://github.com/istio/client-go/blob/21751e6cf0fea131872230940d95c40508aa0a4f/pkg/clientset/versioned/typed/networking/v1alpha3/fake/fake_gateway.gen.go#L21

### CODE REVIEW

**Comment by nrjpoddar** [comment]
@skaslev do you a test/example you can add that verifies fake client, we can make sure that code compiles as part of the CI process so this doesn't break again.

Please also cherry-pick this to release-1.4 branch. Thanks!

**Comment by skaslev** [comment]
> @skaslev do you a test/example you can add that verifies fake client, we can make sure that code compiles as part of the CI process so this doesn't break again.

I don't have one atm. This was noticed while migrating Knative to use istio.io/client-go instead of its own apis for istio, see knative/serving#6041. Some of Knative tests were hanging and the informer was logging errors when using the fake clientset.

I'll try to think of a good test for this.

> 
> Please also cherry-pick this to release-1.4 branch.

Will do. Is there a documentation of the process how to do that?

**Comment by nrjpoddar** [comment]
> Will do. Is there a documentation of the process how to do that?

Yes, you just need to add the label "cherry-pick/release-1.4" to your PRs. I'm not sure if you're allowed to do that if you're not a member, give it a try. If it doesn't work I can do it for you.

**Comment by skaslev** [comment]
/hold

There are two issues with this PR:
  1. gencheck_client-go is failing because its using kubetype-gen before istio/tools#549 got merged. Probably some container image should be updated before merging this?
  2. lint_client-go is failing because new kubetype-gen generated `doc.go` have no license header and `doc.gen.go` were ignored by `lint-copyright-banner`. I can either make target `lint-copyright-banner` in Makefile.common.mk from https://github.com/istio/common-files ignore `doc.go` files, or have kubetype-gen output copyright header for `doc.go` files. Suggestions?

cc @jwendell @nrjpoddar

**Comment by nrjpoddar** [comment]
@skaslev you would need to manually run `make update-common` to grab the latest common files., until we automate this process. @geeknoid FYI.

**Comment by skaslev** [comment]
> @skaslev you would need to manually run `make update-common` to grab the latest common files., until we automate this process. @geeknoid FYI.

Sure, waiting on istio/common-files#149 to get merged first.

**Comment by jasonwzm** [comment]
The image in test-infra also need to be changed.

**Comment by skaslev** [comment]
Since istio/common-files#149 is being pushed back, I changed `header.go.txt` so now all k8s client generated files have a copyright notice.

As @jasonwzm mentioned, for gencheck_client-go to pass the image in test-infra needs to be pushed and updated but I don't think I have permissions for this.

**Comment by sdake** [comment]
> Since [istio/common-files#149](https://github.com/istio/common-files/pull/149) is being pushed back, I updated `header.go.txt` so now all k8s client generated files have copyright banners.
> 
> As @jasonwzm mentioned, for `gencheck_client-go` to pass the image in test-infra needs to be pushed and updated with latest `istio/tools` but I don't think I have permissions for this.

@skaslev please submit a PR to test-infra to make the change. Anyone has permission to submit a PR.  If the PR is acceptable to the T&R reviewers, the PR will be merged pretty quickly.

I would help out here, but I am boarding a plane in a few hours and really busy for the next few days.

Modify this line: https://github.com/istio/test-infra/blob/master/prow/config/jobs/client-go.yaml#L4

with the latest image from:
https://console.cloud.google.com/gcr/images/istio-testing/GLOBAL/build-tools?gcrImageListsize=30

which happens to have the tag:
`master-2019-11-15T13-58-33`

After that change to istio/test-infra, in the TLD run `make gen`.  This will convert the client-go.yaml prow human-readable config into prow-less-human-readable parsed output.

You should end up with two files changed in your PR.  Push when ready.

I will review if you like.  Pass the information along 😀 

Cheers
-steve

**Comment by skaslev** [comment]
Thank for the help @sdake! Just sent istio/test-infra#2108 for review.

**Comment by skaslev** [comment]
@geeknoid can you review this PR? 

The only functional change is in this [commit](https://github.com/istio/client-go/pull/22/commits/8387b42bcfa5db7b3fa0f7bd340951a3da16086a), everything else is auto generated.

**Comment by jasonwzm** [comment]
@skaslev Thanks for making the change! A manual cherrypick is probably needed to 1.4.

**Pull request merged**
